name: shift-assignment

on:
  push:
    paths:
      - "shift-assignment/**"
    branches:
      - stable

jobs:
  shift-assignment:
    uses: ./.github/workflows/nextmv.yml
    with:
      APP_ID: shift-assignment-pyomo
      APP_DIRECTORY: ./shift-assignment
    secrets:
      NEXTMV_API_KEY: ${{ secrets.NEXTMV_API_KEY }}
