name: vehicle-routing

on:
  push:
    paths:
      - "./vehicle-routing/**.py"
    branches:
      - stable

jobs:
  vehicle-routing:
    uses: ./.github/workflows/nextmv.yml
    with:
      APP_ID: vehicle-routing-pyomo
      APP_DIRECTORY: ./vehicle-routing
