name: vehicle-routing

on:
  push:
    paths:
      - "vehicle-routing/**"
    branches:
      - stable

jobs:
  vehicle-routing:
    uses: ./.github/workflows/nextmv.yml
    with:
      APP_ID: farmshare-ortools
      APP_DIRECTORY: ./vehicle-routing
    secrets:
      NEXTMV_API_KEY: ${{ secrets.NEXTMV_API_KEY }}
